version: "3.9"

services:
  website:
    container_name: Ehv_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:80
    environment:
      - CHOKIDAR_USEPOLLING=true
