apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehv-website
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ehv-website
  template:
    metadata:
      labels:
        app: ehv-website
    spec:
      containers:
        - name: ehv-website
          image: vincentdarwinkel/ehv-website
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ehv-website
spec:
  type: LoadBalancer
  ports:
    - name: ehv-website
      port: 80
      targetPort: 80
  selector:
    app: ehv-website
